[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
reclaim = "sak9EpYPZBz2Mx1prWRT62PJwit3PGnoyw9d7Ep5jpS"
[programs.devnet]
base = "sak9EpYPZBz2Mx1prWRT62PJwit3PGnoyw9d7Ep5jpS"
reclaim = "rEcLDWaVLaymz82eGr6cutosPxE6SEzw6q4pbtLuyqf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/code/reclaim/sak9EpYPZBz2Mx1prWRT62PJwit3PGnoyw9d7Ep5jpS.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
